# appveyor.yml
version: 1.0.{build}
image: Visual Studio 2019

platform:
  - x64

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  CONFIGURATION: Release
  ARTIFACTS_DIR: artifacts
  QT_DIR: C:\Qt\5.15.2\msvc2019_64

clone_depth: 1

install:
  - set PATH=%QT_DIR%\bin;%PATH%

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - cd client
  - qmake
  - jom /J 4
  - cd ..

  - cd server
  - qmake
  - jom /J 4
  - cd ..

after_build:
  - mkdir %ARTIFACTS_DIR%
  - copy client\release\dynablaster.exe %ARTIFACTS_DIR%\dynablaster.exe
  - copy server\release\dynablaster_server.exe %ARTIFACTS_DIR%\server.exe
  - copy client\lib64\*.dll %ARTIFACTS_DIR%\
  - for %I in (Qt5Core Qt5Gui Qt5Network Qt5Widgets) do copy %QT_DIR%\bin\%I.dll %ARTIFACTS_DIR%\
  - xcopy client\data %ARTIFACTS_DIR%\data\ /E /I /Q /Y

artifacts:
  - path: artifacts
    name: Dynablaster Revenge
    type: auto
