# appveyor.yml
version: 1.0.{build}
image: Visual Studio 2019

platform:
  - x64

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  CONFIGURATION: Release
  ARTIFACTS_DIR: artifacts
  QT_DIR: C:\Qt\5.15.2\msvc2019_64

clone_depth: 1

install:
  - set PATH=%QT_DIR%\bin;%PATH%

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - cd client
  - qmake
  - nmake
  - cd ..

  - cd server
  - qmake
  - nmake
  - cd ..

after_build:
  - mkdir %ARTIFACTS_DIR%
  - copy client\release\dynablaster.exe %ARTIFACTS_DIR%\
  - copy server\release\server.exe %ARTIFACTS_DIR%\
  - copy client\lib64\*.dll %ARTIFACTS_DIR%\
  - xcopy client\data %ARTIFACTS_DIR%\data\ /E /I /Q /Y
  - cd %ARTIFACTS_DIR%
  - %QT_DIR%\bin\windeployqt.exe dynablaster.exe
  - %QT_DIR%\bin\windeployqt.exe server.exe

artifacts:
  - path: artifacts
    name: Dynablaster Revenge
    type: auto
